### ISSUE TITLE
Post CreateをKey Bindingで設定。

### ISSUE THREAD

**Issue by unagui0219** [unagui0219/error-recorder#21]
# Overview
SidebarのPostCreateページをコマンドで呼び出せるようにしたい。

# Expected behavior
何かしらのコマンドを打ち込むと、Post Createページが呼び出される。

**Comment by reki204** [comment]
@unagui0219 
コマンドはコマンドパレッドからという認識であってますか？

**Comment by unagui0219** [comment]
@reki204 いや、キーバインディングのほうのコマンドのこと

**Comment by unagui0219** [comment]
実装完了
